---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/planes":
    get:
      summary: list planes
      tags:
      - Planes
      responses:
        '200':
          description: successful
    post:
      summary: create plane
      tags:
      - Planes
      parameters: []
      responses:
        '201':
          description: Plane created!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: string
                description:
                  type: string
                registration:
                  type: string
                cruise_speed:
                  type: integer
                tour_price:
                  type: integer
                picture:
                  type: string
              required:
              - model
              - description
              - tour_price
              - picture
              - registration
              - cruise_speed
  "/api/v1/planes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show plane
      tags:
      - Planes
      responses:
        '200':
          description: successful
    delete:
      summary: delete plane
      tags:
      - Planes
      responses:
        '200':
          description: successful
  "/api/v1/planes/{plane_id}/reservations":
    parameters:
    - name: plane_id
      in: path
      description: plane_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/planes/{plane_id}/reservations/{id}":
    parameters:
    - name: plane_id
      in: path
      description: plane_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
