---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/planes":
    get:
      summary: list planes
      responses:
        '200':
          description: successful
    post:
      summary: create plane
      responses:
        '200':
          description: successful
  "/api/v1/planes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: model
      in: path
      description: Plane model
      required: true
      schema:
        type: string
    - name: description
      in: path
      description: Plane description
      required: true
      schema:
        type: string
    - name: tour_price
      in: path
      description: Tour cost
      required: true
      schema:
        type: string
    get:
      summary: show plane
      responses:
        '200':
          description: successful
    delete:
      summary: delete plane
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
